minor changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -188,10 +188,6 @@ jobs:
         if: steps.cache-android-sdk.outputs.cache-hit != 'true'
         run: sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"
 
-      - name: Prepare keystore
-        run: |
-          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > /root/release.keystore
-
       - name: Set up Godot editor settings
         run: |
           mkdir -p ~/.config/godot/
@@ -202,20 +198,21 @@ jobs:
           echo 'export/android/force_system_user = false' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
           echo 'export/android/timestamping_authority_url = ""' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
           echo 'export/android/shutdown_adb_on_exit = true' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
-          echo 'export/android/release = "/root/release.keystore"' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
-          echo 'export/android/release_keystore_user = "${{ secrets.RELEASE_KEYSTORE_USER }}"' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
-          echo 'export/android/release_keystore_pass = "${{ secrets.RELEASE_KEYSTORE_PASS }}"' >> ~/.config/godot/editor_settings-${GODOT_VERSION}.tres
       
-      - name: Android Build
-        # env:
-        #   GODOT_ANDROID_KEYSTORE_RELEASE_PATH: /root/release.keystore
-        #   GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.RELEASE_KEYSTORE_USER }}
-        #   GODOT_ANDROID_KEYSTORE_RELEASE_PASS: ${{ secrets.RELEASE_KEYSTORE_PASS }}
+      - name: Prepare keystore
         run: |
-          ls -la /root/release.keystore || echo "Keystore file not found"
+          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > $HOME/release.keystore
+
+      - name: Android Build
+        env:
+          GODOT_ANDROID_KEYSTORE_RELEASE_PATH: $HOME/release.keystore
+          GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.RELEASE_KEYSTORE_USER }}
+          GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD }}
+        run: |
+          ls -la $HOME/release.keystore || echo "Keystore file not found"
           echo "GODOT_ANDROID_KEYSTORE_RELEASE_PATH is set to: $GODOT_ANDROID_KEYSTORE_RELEASE_PATH"
           echo "GODOT_ANDROID_KEYSTORE_RELEASE_USER is set: ${{ secrets.RELEASE_KEYSTORE_USER != '' }}"
-          echo "GODOT_ANDROID_KEYSTORE_RELEASE_PASS is set: ${{ secrets.RELEASE_KEYSTORE_PASS != '' }}"
+          echo "GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD is set: ${{ secrets.RELEASE_KEYSTORE_PASS != '' }}"
 
           mkdir -v -p build/android
           EXPORT_DIR="$(readlink -f build)"
